# Generated by Django 2.2.9 on 2020-02-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(height_field=100, null=True, upload_to='logos', width_field=100),
        ),
    ]
